
  // This file was autogenerated by dynamically running setEnv.ts and using dotenv for managing API key secrecy
  export const environment = {
    production: undefined,
    apiUrl: "undefined",
    gapi: {
      clientId: "undefined",
      redirectUri: "undefined"
    },
    firebase: {
      apiKey: "undefined",
      authDomain: "undefined",
      databaseURL: "undefined",
      projectId: "undefined",
      storageBucket: "undefined",
      messagingSenderId: "undefined",
      appId: "undefined",
      measurementId: "undefined"
    }
  }
